alter table if exists pipeline_steps rename to pipeline_steps_legacy;
alter table if exists pipeline_configurations rename to pipeline_configurations_legacy;

alter sequence if exists pipeline_steps_id_seq rename to pipeline_steps_legacy_id_seq;
alter sequence if exists pipeline_configurations_id_seq rename to pipeline_configurations_legacy_id_seq;

create table pipelines (
    id bigint generated by default as identity,
    project_id bigint not null references projects (id) on delete cascade,
    name varchar(120) not null,
    description varchar(1000),
    status varchar(32) not null,
    trigger_type varchar(32) not null,
    branch_name varchar(200) not null,
    version integer not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint pk_pipelines_v4 primary key (id),
    constraint uk_pipelines_v4_project_name unique (project_id, name),
    constraint ck_pipelines_status check (
        status in ('DRAFT', 'ACTIVE', 'DISABLED', 'ARCHIVED')
    ),
    constraint ck_pipelines_trigger_type check (
        trigger_type in ('MANUAL', 'WEBHOOK', 'SCHEDULE')
    )
);

create table pipeline_stages (
    id bigint generated by default as identity,
    pipeline_id bigint not null references pipelines (id) on delete cascade,
    name varchar(120) not null,
    display_name varchar(120) not null,
    sort_order integer not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint pk_pipeline_stages_v4 primary key (id),
    constraint uk_pipeline_stages_v4_name unique (pipeline_id, name),
    constraint uk_pipeline_stages_v4_order unique (pipeline_id, sort_order)
);

create table pipeline_steps (
    id bigint generated by default as identity,
    pipeline_id bigint not null references pipelines (id) on delete cascade,
    stage_id bigint not null references pipeline_stages (id) on delete cascade,
    step_key varchar(120) not null,
    name varchar(120) not null,
    display_name varchar(120) not null,
    type varchar(80) not null,
    sort_order integer not null,
    config_json text not null,
    enabled boolean not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint pk_pipeline_steps_v4 primary key (id),
    constraint uk_pipeline_steps_v4_key unique (pipeline_id, step_key),
    constraint uk_pipeline_steps_v4_order unique (stage_id, sort_order),
    constraint ck_pipeline_steps_type check (
        type in ('CHECKOUT', 'SHELL', 'TEST', 'SONAR_SCAN', 'BUILD_IMAGE', 'PUSH_IMAGE')
    )
);

create index idx_pipelines_v4_project_id on pipelines (project_id);
create index idx_pipeline_stages_v4_pipeline_id on pipeline_stages (pipeline_id);
create index idx_pipeline_steps_v4_pipeline_id on pipeline_steps (pipeline_id);
create index idx_pipeline_steps_v4_stage_id on pipeline_steps (stage_id);
