create table jenkins_connections (
    id bigint primary key generated by default as identity,
    name varchar(120) not null,
    base_url varchar(500) not null,
    username varchar(200) not null,
    api_token_plain text,
    verification_status varchar(32) not null,
    last_verified_at timestamptz,
    last_verification_message varchar(1000),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_jenkins_connections_name unique (name),
    constraint ck_jenkins_connections_verification_status check (
        verification_status in ('UNVERIFIED', 'VERIFIED', 'FAILED')
    )
);
