alter table if exists build_results rename to build_results_legacy;
alter table if exists step_runs rename to step_runs_legacy;
alter table if exists pipeline_runs rename to pipeline_runs_legacy;

create table pipeline_runs (
    id bigint generated by default as identity,
    pipeline_id bigint not null references pipelines (id),
    project_id bigint not null references projects (id),
    jenkins_connection_id bigint not null references jenkins_connections (id),
    run_number integer not null,
    status varchar(32) not null,
    trigger_type varchar(32) not null,
    branch varchar(200) not null,
    commit_sha varchar(200),
    jenkins_job_name varchar(500) not null,
    jenkins_queue_url varchar(1000),
    jenkins_build_number integer,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint pk_pipeline_runs_v6 primary key (id),
    constraint uk_pipeline_runs_v6_number unique (pipeline_id, run_number),
    constraint ck_pipeline_runs_v6_status check (
        status in ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELED')
    ),
    constraint ck_pipeline_runs_v6_trigger_type check (
        trigger_type in ('MANUAL', 'WEBHOOK', 'SCHEDULE')
    )
);

create index idx_pipeline_runs_v6_pipeline_id on pipeline_runs (pipeline_id);
create index idx_pipeline_runs_v6_project_id on pipeline_runs (project_id);
create index idx_pipeline_runs_v6_jenkins_connection_id on pipeline_runs (jenkins_connection_id);
create index idx_pipeline_runs_v6_status on pipeline_runs (status);
