create table jenkins_jobs (
    id bigint generated by default as identity,
    pipeline_id bigint not null references pipelines (id) on delete cascade,
    jenkins_connection_id bigint not null references jenkins_connections (id),
    job_name varchar(500) not null,
    job_type varchar(32) not null,
    config_hash varchar(128) not null,
    last_synced_at timestamptz,
    last_sync_status varchar(32) not null,
    last_sync_message varchar(1000),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint pk_jenkins_jobs primary key (id),
    constraint uk_jenkins_jobs_pipeline_connection unique (pipeline_id, jenkins_connection_id),
    constraint uk_jenkins_jobs_connection_name unique (jenkins_connection_id, job_name),
    constraint ck_jenkins_jobs_type check (
        job_type in ('FREESTYLE')
    ),
    constraint ck_jenkins_jobs_sync_status check (
        last_sync_status in ('PENDING', 'SYNCED', 'FAILED')
    )
);

create index idx_jenkins_jobs_pipeline_id on jenkins_jobs (pipeline_id);
create index idx_jenkins_jobs_connection_id on jenkins_jobs (jenkins_connection_id);
