CREATE TABLE pipeline_run_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id BIGINT NOT NULL REFERENCES pipeline_runs(id),
    external_log_url VARCHAR(1000),
    log_excerpt TEXT NOT NULL,
    log_size_bytes BIGINT NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pipeline_run_logs_run_id ON pipeline_run_logs(pipeline_run_id);
