apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-runner
  namespace: bipeline-ci
  labels:
    app.kubernetes.io/part-of: bipeline
    app.kubernetes.io/component: ci
automountServiceAccountToken: false
