package com.pipeline.platform.pipeline.application.service;

import java.util.Map;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.pipeline.platform.jenkins.application.model.JenkinsJobDefinition;
import com.pipeline.platform.pipeline.application.model.CheckoutSpec;
import com.pipeline.platform.pipeline.domain.Pipeline;
import com.pipeline.platform.pipeline.domain.PipelineStage;
import com.pipeline.platform.pipeline.domain.PipelineStep;
import com.pipeline.platform.pipeline.domain.StepType;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class PipelineRunJobFactory {

    private static final TypeReference<Map<String, Object>> CONFIG_TYPE = new TypeReference<>() {
    };

    @Autowired
    private ObjectMapper objectMapper;

    public JenkinsJobDefinition toFreestyleJob(Pipeline pipeline, CheckoutSpec checkoutSpec) {
        String shellScript = shellScript(pipeline, checkoutSpec);
        return new JenkinsJobDefinition(
                jobName(pipeline),
                "FREESTYLE",
                sha256(shellScript),
                "Generated by pipeline platform for pipeline " + pipeline.name(),
                shellScript
        );
    }

    private String jobName(Pipeline pipeline) {
        return "pipeline-%d-%d-%s".formatted(
                pipeline.projectId(),
                pipeline.id(),
                pipeline.name().replaceAll("[^A-Za-z0-9_.-]", "-")
        );
    }

    private String shellScript(Pipeline pipeline, CheckoutSpec checkoutSpec) {
        StringBuilder script = new StringBuilder();
        script.append("set -e\n");
        script.append("echo 'Pipeline: ").append(escapeShellText(pipeline.name())).append("'\n");
        script.append("echo 'Branch: ").append(escapeShellText(checkoutSpec.branch())).append("'\n");
        appendCheckout(script, checkoutSpec);
        for (PipelineStage stage : pipeline.stages()) {
            appendStage(script, stage);
        }
        return script.toString();
    }

    private void appendCheckout(StringBuilder script, CheckoutSpec checkoutSpec) {
        script.append("echo 'Checkout source repository'\n");
        script.append("rm -rf source\n");
        script.append("cat > .git-askpass.sh <<'PIPELINE_GIT_ASKPASS'\n");
        script.append("#!/bin/sh\n");
        script.append("case \"$1\" in\n");
        script.append("  *Username*) printf '%s\\n' '").append(escapeShellText(checkoutSpec.username())).append("' ;;\n");
        script.append("  *Password*) printf '%s\\n' '").append(escapeShellText(checkoutSpec.secret())).append("' ;;\n");
        script.append("  *) printf '%s\\n' '' ;;\n");
        script.append("esac\n");
        script.append("PIPELINE_GIT_ASKPASS\n");
        script.append("chmod 700 .git-askpass.sh\n");
        script.append("GIT_ASKPASS=\"$PWD/.git-askpass.sh\" GIT_TERMINAL_PROMPT=0 ");
        script.append("git clone --branch '").append(escapeShellText(checkoutSpec.branch())).append("' ");
        script.append("--single-branch '").append(escapeShellText(checkoutSpec.remoteUrl())).append("' source\n");
        script.append("rm -f .git-askpass.sh\n");
        script.append("cd source\n");
        if (!".".equals(checkoutSpec.contextDirectory())) {
            script.append("cd '").append(escapeShellText(checkoutSpec.contextDirectory())).append("'\n");
        }
    }

    private void appendStage(StringBuilder script, PipelineStage stage) {
        script.append("echo 'Stage: ").append(escapeShellText(stage.displayName())).append("'\n");
        for (PipelineStep step : stage.steps()) {
            appendStep(script, step);
        }
    }

    private void appendStep(StringBuilder script, PipelineStep step) {
        if (!step.enabled()) {
            return;
        }
        script.append("echo 'Step: ").append(escapeShellText(step.displayName())).append("'\n");
        if (step.type() == StepType.SHELL) {
            script.append(shellCommand(step)).append("\n");
            return;
        }
        script.append("echo 'Step type ").append(step.type()).append(" is not executable in MVP yet'\n");
    }

    private String shellCommand(PipelineStep step) {
        Object command = stepConfig(step).get("command");
        if (command == null || command.toString().isBlank()) {
            return "echo 'No shell command configured'";
        }
        return command.toString();
    }

    private Map<String, Object> stepConfig(PipelineStep step) {
        try {
            return objectMapper.readValue(step.configJson(), CONFIG_TYPE);
        } catch (JsonProcessingException exception) {
            return Map.of();
        }
    }

    private String escapeShellText(String value) {
        if (value == null) {
            return "";
        }
        return value.replace("'", "'\"'\"'");
    }

    private String sha256(String value) {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256")
                    .digest(value.getBytes(StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder();
            for (byte item : digest) {
                hex.append("%02x".formatted(item));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is not available", exception);
        }
    }
}
